spring.application.name=gestrun
spring.profiles.active=${APP_PROFILE:dev}

# URL do Swagger UI
springdoc.swagger-ui.path=/docs
# URL do endpoint JSON/YAML da especificação OpenAPI
springdoc.api-docs.path=/api-docs

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

springdoc.swagger-ui.tagsSorter=alpha
springdoc.writer-with-order-by-keys=true
